// import React from "react";
// import { Link } from "react-router-dom";
// import './Nav.css'

// const Nav = () => {
//     return(
//         <div className="nav">
        
//                 <Link className="link" to='/acceuil'> <i class="fa-solid fa-user"></i></Link>
//                 <Link className="link" to='/acceuil'><i class="fa-solid fa-user"></i></Link>
//                 <Link className="link" to='/'> <i class="fa-solid fa-house"></i> </Link>
//                 <Link className="link" to='/acceuil'><i class="fa-solid fa-file"></i></Link>
//                 <Link className="link" to='/acceuil'> <i class="fa-solid fa-bookmark"></i></Link>
            
//         </div>
//     )
// }
// export default Nav

import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import { Link } from "react-router-dom";
import Paper from '@mui/material/Paper';
import PersonIcon from '@mui/icons-material/Person';
import HomeIcon from '@mui/icons-material/Home';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import DashboardIcon from '@mui/icons-material/Dashboard';


export default function FixedBottomNavigation() {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef(null);


 

  return (
    <Box sx={{ pb: 7 }} ref={ref}>
      <CssBaseline />
     
      <Paper sx={{ position: 'fixed', bottom: 0, left: 0, right: 0 }} elevation={3}>
        <BottomNavigation
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <Link className="link" to='/dashboard'><BottomNavigationAction label="Dashboard" icon={<DashboardIcon />} /></Link>
          <Link className="link" to='/quartiers'><BottomNavigationAction label="Localisation" icon={<LocationOnIcon />} /></Link>
          <Link className="link" to='/acceuil'><BottomNavigationAction label="Accueil" icon={<HomeIcon />} /></Link>
          <Link className="link" to='/acceuil'><BottomNavigationAction label="Compte" icon={<PersonIcon />} /></Link>
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

// const messageExamples = [
//   {
//     primary: 'Brunch this week?',
//     secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     primary: 'Birthday Gift',
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: '/static/images/avatar/1.jpg',
//   },
//   {
//     primary: 'Recipe to try',
//     secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
//     person: '/static/images/avatar/2.jpg',
//   },
//   {
//     primary: 'Yes!',
//     secondary: 'I have the tickets to the ReactConf for this year.',
//     person: '/static/images/avatar/3.jpg',
//   },
//   {
//     primary: "Doctor's Appointment",
//     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
//     person: '/static/images/avatar/4.jpg',
//   },
//   {
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     primary: 'Summer BBQ',
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: '/static/images/avatar/1.jpg',
//   },
// ];


// import * as React from 'react';
// import Tabs from '@mui/material/Tabs';
// import Tab from '@mui/material/Tab';
// import PhoneIcon from '@mui/icons-material/Phone';
// import FavoriteIcon from '@mui/icons-material/Favorite';
// import PersonPinIcon from '@mui/icons-material/PersonPin';
// import PhoneMissedIcon from '@mui/icons-material/PhoneMissed';

// export default function IconTabs() {
//   const [value, setValue] = React.useState(0);

//   const handleChange = (event, newValue) => {
//     setValue(newValue);
//   };

//   return (
//     <Tabs
//       value={value}
//       onChange={handleChange}
//       aria-label="icon position tabs example"
//     >
//       <Tab icon={<PhoneIcon />} label="top" />
//       <Tab icon={<PhoneMissedIcon />} iconPosition="start" label="start" />
//       <Tab icon={<FavoriteIcon />} iconPosition="end" label="end" />
//       <Tab icon={<PersonPinIcon />} iconPosition="bottom" label="bottom" />
//     </Tabs>
//   );
// }